# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Effecting Affordances
description: "There are Affordances in every environment. It takes Effectivities to use them. Exploring the intersection of perception frameworks and complex systems: this blog examines how effectivities (our capabilities) interact with affordances (environmental possibilities) to shape our approach to technical architecture and troubleshooting. Drawing from evolutionary psychology, systems thinking, and cognitive science, we investigate how mental models influence our ability to navigate increasingly complex digital landscapes—where the balance between reality-based understanding and fitness-based heuristics determines our effectiveness in designing resilient, antifragile systems."
github_username: assimilatereality
baseurl: ""
url: "https://assimilatereality.github.io"
sass:
  sass_dir: assets/css

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
